apiVersion: v1
kind: Namespace
metadata:
  name: kube-pfs-observability
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-pfs-prometheus-config
  namespace: kube-pfs-observability
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
    scrape_configs:
      - job_name: kube-pfs-mds
        static_configs:
          - targets: ["kube-pfs-mds.kube-pfs-system.svc.cluster.local:9101"]
      - job_name: kube-pfs-ost
        static_configs:
          - targets: ["kube-pfs-ost-0.kube-pfs-system.svc.cluster.local:9102", "kube-pfs-ost-1.kube-pfs-system.svc.cluster.local:9102", "kube-pfs-ost-2.kube-pfs-system.svc.cluster.local:9102"]
      - job_name: kube-pfs-csi-controller
        static_configs:
          - targets: ["kube-pfs-csi-controller.kube-pfs-system.svc.cluster.local:9103"]
      - job_name: kube-pfs-csi-node
        static_configs:
          - targets: ["kube-pfs-csi-node.kube-pfs-system.svc.cluster.local:9104"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-pfs-prometheus
  namespace: kube-pfs-observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-pfs-prometheus
  template:
    metadata:
      labels:
        app: kube-pfs-prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.55.1
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus
      volumes:
        - name: config
          configMap:
            name: kube-pfs-prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  name: kube-pfs-prometheus
  namespace: kube-pfs-observability
spec:
  selector:
    app: kube-pfs-prometheus
  ports:
    - port: 9090
      targetPort: 9090
